### ISSUE TITLE
Utility for knowing if an `Identifier` is a reference to a binding

### ISSUE THREAD

**Issue by Rich-Harris** [sarsamurmu/estree-toolkit#10]
When traversing an AST, is there an easy way to know if an `Identifier` node references a binding or not? In other words, this code...

```js
const ast = parse(`foo; obj.bar`);

traverse(ast, {
  $: { scope: true },
  Identifier(path) {
    console.log(path.node.name);
  }
});
```

...will log this...

```
foo
obj
bar
```

...but only `foo` and `obj` are binding references. I have a package for this — [is-reference](https://www.npmjs.com/package/is-reference) — but it would be awesome if there was a way to do this within `estree-toolkit`. Thank you!

**Comment by sarsamurmu** [comment]
It's possible, currently there's no built-in utility function but for now you can make yourself one
```js
const ast = parseModule(`
const foo = 0, obj = {};
const bar = 0;

foo;
obj.bar;
`);

/**
 * @param {NodePath} path 
 */
const isReference = (path) => {
  const binding = path.scope.getBinding(path.node.name);
  if (binding != null) {
    return path === binding.identifierPath || binding.references.includes(path)
  }
  return false
}

traverse(ast, {
  $: { scope: true },
  Identifier(path) {
    console.log(path.node.name, isReference(path))
  }
})
```
Output
```
foo true
obj true
bar true
foo true
obj true
bar false
```

**Comment by Rich-Harris** [comment]
Wonderful, thanks! That works for us — I'll leave this issue open in case you intend to expose a utility like that, but otherwise please consider this resolved

**Comment by sarsamurmu** [comment]
Just leaving this issue open, I will add this functionality to the library later

**Comment by sarsamurmu** [comment]
https://estree-toolkit.netlify.app/utilities#isreferencepath-includeglobals
