### ISSUE TITLE
Property.key might not be a PrivateIdentifier

### ISSUE THREAD

**Issue by HKGx** [sarsamurmu/estree-toolkit#13]
https://astexplorer.net/#/gist/d3b754be4002e2073a4edf60cef78b90/999019efedfc3882485ab2be3340e217b9644b42

```js
define({
  foo: null,
  bar: null,
})
```

Meriyah reports that both "foo" and "bar" are simple Identifiers and not PrivateIdentifiers.

**Comment by sarsamurmu** [comment]
Are these supposed to be PrivateIdentifiers? Can you elaborate?

**Comment by HKGx** [comment]
> Are these supposed to be PrivateIdentifiers?
I don't really know. It's just how mariyah handles it. :shrug:

**Comment by sarsamurmu** [comment]
Closing it. If still have the problem then please reopen the issue.
