### ISSUE TITLE
JSX visitor keys

### ISSUE THREAD

**Issue by aleclarson** [sarsamurmu/estree-toolkit#3]
How do I add JSX support

**Comment by sarsamurmu** [comment]
This project is not that extensible yet. For now what you can do is fork this project and add JSX support by yourself. Ask me if you need any help :)

**Comment by sarsamurmu** [comment]
This is how you can add JSX support to your fork
- Install `@types/estree-jsx` as dependency
- Change all `estree` imports to `estree-jsx` import, in whole project
- Open `definition.ts` and add missing definitions, typescript would automatically inform you which types are missing
- Open `scope.ts` and add missing crawlers. Like definitions, TypeScript would inform you which types you're missing

**Comment by sarsamurmu** [comment]
JSX is now supported in the latest version.
