### ISSUE TITLE
Validation fails with UpdateExpression on ArrowFunction body

### ISSUE THREAD

**Issue by trueadm** [sarsamurmu/estree-toolkit#6]
Given the below:

```js
const x = () => foo++;
```

This fails and gives me some strange validation error about a circular structure to JSON. I assume the issue is assuming arrow functions must have block statements.

**Comment by sarsamurmu** [comment]
I'm looking into it.

**Comment by sarsamurmu** [comment]
I'm unable to reproduce this issue, here is my code
```js
const { parseModule } = require('meriyah')
const astring = require('astring')

const ast = parseModule(`
  const x = () => {};
`)

traverse(ast, {
  $: { scope: true, validateNodes: true },
  ArrowFunctionExpression(path) {
    path.get('body').replaceWith(b.updateExpression('++', b.identifier('foo'), false))
  }
})

console.log(astring.generate(ast))
// Output: const x = () => foo++;
```

Can you share your code?

**Comment by trueadm** [comment]
Your arrow function has a `BlockStatement`. Try making it an expression instead;

```js
const ast = parseModule(`
  let y = 0;
  const x = () => y++;
`)
```

**Comment by sarsamurmu** [comment]
It works on my system, I also ran it on Replit - https://replit.com/@SarsaMurmu/TastyGivingVendors#index.js. It works there too. I'm not sure what is causing this issue.

**Comment by trueadm** [comment]
Ah, I think I know what it might be. It's because my nodes have an additional `parent` property and it seems the validation logic must be looking at this property.
