### ISSUE TITLE
Question on how to construct NodePaths

### ISSUE THREAD

**Issue by not-jan** [sarsamurmu/estree-toolkit#7]
I'm trying to simplify a piece of code. The code looks like this:

```
if (true) {
  console.log("true");
else {
  console.log("false");
}
```

The easiest way of implementing this would be to use the evaluateTruthy function from the utilities but that will only take a path. Is there any way of reusing that code for my purposes?

**Comment by not-jan** [comment]
Thank you! :)

**Comment by sarsamurmu** [comment]
I was using `consequent` instead of alternate in `else`. I updated the code to fix that.
