### ISSUE TITLE
Enable a way to skip traversal of all children

### ISSUE THREAD

**Issue by trueadm** [sarsamurmu/estree-toolkit#9]
Today `path.skip()` only applies to the current node, it would be great to skip the traversal of all children of that given path too.

**Comment by Rich-Harris** [comment]
Or better still, abort all subsequent traversal:

```js
traverse(program, {
  Identifier(path) {
    if (path.node.name === 'Waldo') {
      console.log('found him');
      path.abort();
    }
  }
});
```

**Comment by sarsamurmu** [comment]
We have something similar to abort - https://estree-toolkit.netlify.app/traversal/#stopping-traversal. But it totally stops the traversal, so I don't think it's what you want.

**Comment by sarsamurmu** [comment]
New version has it - `skipChildren`

**Comment by Rich-Harris** [comment]
Fantastic, thanks so much! `this.stop()` is what I was looking for, but `skipChildren` is also super helpful
